; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "易舜云手机"
!define PRODUCT_VERSION "1.0.0"
!define PRODUCT_PUBLISHER "易舜"
!define PRODUCT_WEB_SITE "https://www.ysyos.com/"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\YiShunYun.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "YSY_Release\logo.ico"
!define MUI_UNICON "YSY_Release\logo.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
;!insertmacro MUI_PAGE_LICENSE "License.txt"
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\YiShunYun.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "SimpChinese"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "YSY_Release\YiShunYunInstaller.exe"
InstallDir "$PROGRAMFILES\易舜云手机"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
  File "YSY_Release\zlibwapi.dll"
  File "YSY_Release\YiShunYun.exe"
  CreateDirectory "$SMPROGRAMS\易舜云手机"
  CreateShortCut "$SMPROGRAMS\易舜云手机\易舜云手机.lnk" "$INSTDIR\YiShunYun.exe"
  CreateShortCut "$DESKTOP\易舜云手机.lnk" "$INSTDIR\YiShunYun.exe"
  File "YSY_Release\update.exe"
  File "YSY_Release\swplay_u.lib"
  File "YSY_Release\swplay_u.dll"
  File "YSY_Release\ssleay32.dll"
  File "YSY_Release\QtWebEngineProcess.exe"
  File "YSY_Release\Qt6Widgets.dll"
  File "YSY_Release\Qt6WebEngineWidgets.dll"
  File "YSY_Release\Qt6WebEngineCore.dll"
  File "YSY_Release\Qt6WebChannel.dll"
  File "YSY_Release\Qt6Svg.dll"
  File "YSY_Release\Qt6QuickWidgets.dll"
  File "YSY_Release\Qt6Quick.dll"
  File "YSY_Release\Qt6QmlModels.dll"
  File "YSY_Release\Qt6Qml.dll"
  File "YSY_Release\Qt6PrintSupport.dll"
  File "YSY_Release\Qt6Positioning.dll"
  File "YSY_Release\Qt6OpenGL.dll"
  File "YSY_Release\Qt6Network.dll"
  File "YSY_Release\Qt6Gui.dll"
  File "YSY_Release\Qt6Core.dll"
  File "YSY_Release\opengl32sw.dll"
  File "YSY_Release\logo.ico"
  File "YSY_Release\libeay32.dll"
  File "YSY_Release\libcurl.dll"
  File "YSY_Release\D3Dcompiler_47.dll"
  File /r "YSY_Release\generic"
  File /r "YSY_Release\iconengines"
  File /r "YSY_Release\imageformats"
  ;File /r "YSY_Release\locales"
  File /r "YSY_Release\networkinformation"
  File /r "YSY_Release\platforms"
  File /r "YSY_Release\position"
  ;File /r "YSY_Release\qml"
  File /r "YSY_Release\qmltooling"
  File /r "YSY_Release\resources"
  File /r "YSY_Release\screenshots"
  File /r "YSY_Release\styles"
  File /r "YSY_Release\tls"
  File /r "YSY_Release\translations"
SectionEnd

Section -AdditionalIcons
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\易舜云手机\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\易舜云手机\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\YiShunYun.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\YiShunYun.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) 已成功地从你的计算机移除。"
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "你确实要完全移除 $(^Name) ，其及所有的组件？" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\D3Dcompiler_47.dll"
  Delete "$INSTDIR\libcurl.dll"
  Delete "$INSTDIR\libeay32.dll"
  Delete "$INSTDIR\logo.ico"
  Delete "$INSTDIR\opengl32sw.dll"
  Delete "$INSTDIR\Qt6Core.dll"
  Delete "$INSTDIR\Qt6Gui.dll"
  Delete "$INSTDIR\Qt6Network.dll"
  Delete "$INSTDIR\Qt6OpenGL.dll"
  Delete "$INSTDIR\Qt6Positioning.dll"
  Delete "$INSTDIR\Qt6PrintSupport.dll"
  Delete "$INSTDIR\Qt6Qml.dll"
  Delete "$INSTDIR\Qt6QmlModels.dll"
  Delete "$INSTDIR\Qt6Quick.dll"
  Delete "$INSTDIR\Qt6QuickWidgets.dll"
  Delete "$INSTDIR\Qt6Svg.dll"
  Delete "$INSTDIR\Qt6WebChannel.dll"
  Delete "$INSTDIR\Qt6WebEngineCore.dll"
  Delete "$INSTDIR\Qt6WebEngineWidgets.dll"
  Delete "$INSTDIR\Qt6Widgets.dll"
  Delete "$INSTDIR\QtWebEngineProcess.exe"
  Delete "$INSTDIR\ssleay32.dll"
  Delete "$INSTDIR\swplay_u.dll"
  Delete "$INSTDIR\swplay_u.lib"
  Delete "$INSTDIR\update.exe"
  Delete "$INSTDIR\YiShunYun.exe"
  Delete "$INSTDIR\zlibwapi.dll"
  
  RMDir /r "$INSTDIR\generic"
  RMDir /r "$INSTDIR\iconengines"
  RMDir /r "$INSTDIR\imageformats"
  ;RMDir /r "$INSTDIR\locales"
  RMDir /r "$INSTDIR\networkinformation"
  RMDir /r "$INSTDIR\platforms"
  RMDir /r "$INSTDIR\position"
  ;RMDir /r "$INSTDIR\qml"
  RMDir /r "$INSTDIR\qmltooling"
  RMDir /r "$INSTDIR\resources"
  RMDir /r "$INSTDIR\screenshots"
  RMDir /r "$INSTDIR\styles"
  RMDir /r "$INSTDIR\tls"
  RMDir /r "$INSTDIR\translations"

  Delete "$SMPROGRAMS\易舜云手机\Uninstall.lnk"
  Delete "$SMPROGRAMS\易舜云手机\Website.lnk"
  Delete "$DESKTOP\易舜云手机.lnk"
  Delete "$SMPROGRAMS\易舜云手机\易舜云手机.lnk"

  RMDir "$SMPROGRAMS\易舜云手机"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd
