; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "易舜云手机"
!define PRODUCT_VERSION "1.0.0"
!define PRODUCT_PUBLISHER "长沙易舜信息技术有限公司"
!define PRODUCT_WEB_SITE "https://www.ysyos.com/"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\YiShunYun.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"
!define PRODUCT_STARTMENU_REGVAL "NSIS:StartMenuDir"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "NSISPackage\logo.ico"
!define MUI_UNICON "NSISPackage\logo.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
;!insertmacro MUI_PAGE_LICENSE "License.txt"
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Start menu page
var ICONS_GROUP
!define MUI_STARTMENUPAGE_NODISABLE
!define MUI_STARTMENUPAGE_DEFAULTFOLDER "易舜云手机"
!define MUI_STARTMENUPAGE_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_VALUENAME "${PRODUCT_STARTMENU_REGVAL}"
!insertmacro MUI_PAGE_STARTMENU Application $ICONS_GROUP
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\YiShunYun.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "SimpChinese"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "易舜云手机.exe"
InstallDir "$PROGRAMFILES\易舜云手机"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
  File "NSISPackage\zlibwapi.dll"
  File "NSISPackage\YiShunYun.exe"
  CreateDirectory "$SMPROGRAMS\$ICONS_GROUP"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\易舜云手机.lnk" "$INSTDIR\YiShunYun.exe"
  CreateShortCut "$DESKTOP\易舜云手机.lnk" "$INSTDIR\YiShunYun.exe"
  File "NSISPackage\update.exe"
  File "NSISPackage\swplay_u.lib"
  File "NSISPackage\swplay_u.dll"
  File "NSISPackage\ssleay32.dll"
  File "NSISPackage\QtWebEngineProcess.exe"
  File "NSISPackage\Qt6Widgets.dll"
  File "NSISPackage\Qt6WebEngineWidgets.dll"
  File "NSISPackage\Qt6WebEngineCore.dll"
  File "NSISPackage\Qt6WebChannel.dll"
  File "NSISPackage\Qt6Svg.dll"
  File "NSISPackage\Qt6QuickWidgets.dll"
  File "NSISPackage\Qt6Quick.dll"
  File "NSISPackage\Qt6QmlModels.dll"
  File "NSISPackage\Qt6Qml.dll"
  File "NSISPackage\Qt6PrintSupport.dll"
  File "NSISPackage\Qt6Positioning.dll"
  File "NSISPackage\Qt6OpenGL.dll"
  File "NSISPackage\Qt6Network.dll"
  File "NSISPackage\Qt6Gui.dll"
  File "NSISPackage\Qt6Core.dll"
  File "NSISPackage\opengl32sw.dll"
  File "NSISPackage\logo.ico"
  File "NSISPackage\libeay32.dll"
  File "NSISPackage\libcurl.dll"
  File "NSISPackage\D3Dcompiler_47.dll"
  File "NSISPackage\MSVCR120.dll"
  File "NSISPackage\BluetoothApis.dll"
  File "NSISPackage\bthprops.cpl"
  File /r "NSISPackage\generic"
  File /r "NSISPackage\iconengines"
  File /r "NSISPackage\imageformats"
  ;File /r "NSISPackage\locales"
  File /r "NSISPackage\networkinformation"
  File /r "NSISPackage\platforms"
  File /r "NSISPackage\position"
  ;File /r "NSISPackage\qml"
  File /r "NSISPackage\qmltooling"
  File /r "NSISPackage\resources"
  ;File /r "NSISPackage\screenshots"
  File /r "NSISPackage\styles"
  File /r "NSISPackage\tls"
  File /r "NSISPackage\translations"
SectionEnd

Section -AdditionalIcons
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\YiShunYun.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\YiShunYun.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "${PRODUCT_STARTMENU_REGVAL}" "$ICONS_GROUP"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) 已成功地从你的计算机移除。"
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "你确实要完全移除 $(^Name) ，其及所有的组件？" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  ReadRegStr $ICONS_GROUP ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "${PRODUCT_STARTMENU_REGVAL}"
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\D3Dcompiler_47.dll"
  Delete "$INSTDIR\libcurl.dll"
  Delete "$INSTDIR\libeay32.dll"
  Delete "$INSTDIR\logo.ico"
  Delete "$INSTDIR\opengl32sw.dll"
  Delete "$INSTDIR\Qt6Core.dll"
  Delete "$INSTDIR\Qt6Gui.dll"
  Delete "$INSTDIR\Qt6Network.dll"
  Delete "$INSTDIR\Qt6OpenGL.dll"
  Delete "$INSTDIR\Qt6Positioning.dll"
  Delete "$INSTDIR\Qt6PrintSupport.dll"
  Delete "$INSTDIR\Qt6Qml.dll"
  Delete "$INSTDIR\Qt6QmlModels.dll"
  Delete "$INSTDIR\Qt6Quick.dll"
  Delete "$INSTDIR\Qt6QuickWidgets.dll"
  Delete "$INSTDIR\Qt6Svg.dll"
  Delete "$INSTDIR\Qt6WebChannel.dll"
  Delete "$INSTDIR\Qt6WebEngineCore.dll"
  Delete "$INSTDIR\Qt6WebEngineWidgets.dll"
  Delete "$INSTDIR\Qt6Widgets.dll"
  Delete "$INSTDIR\QtWebEngineProcess.exe"
  Delete "$INSTDIR\ssleay32.dll"
  Delete "$INSTDIR\swplay_u.dll"
  Delete "$INSTDIR\swplay_u.lib"
  Delete "$INSTDIR\update.exe"
  Delete "$INSTDIR\YiShunYun.exe"
  Delete "$INSTDIR\zlibwapi.dll"
  Delete "$INSTDIR\MSVCR120.dll"
  Delete "$INSTDIR\BluetoothApis.dll"
  Delete "$INSTDIR\bthprops.cpl"
  
  RMDir /r "$INSTDIR\generic"
  RMDir /r "$INSTDIR\iconengines"
  RMDir /r "$INSTDIR\imageformats"
  ;RMDir /r "$INSTDIR\locales"
  RMDir /r "$INSTDIR\networkinformation"
  RMDir /r "$INSTDIR\platforms"
  RMDir /r "$INSTDIR\position"
  ;RMDir /r "$INSTDIR\qml"
  RMDir /r "$INSTDIR\qmltooling"
  RMDir /r "$INSTDIR\resources"
  RMDir /r "$INSTDIR\screenshots"
  RMDir /r "$INSTDIR\styles"
  RMDir /r "$INSTDIR\tls"
  RMDir /r "$INSTDIR\translations"

  Delete "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk"
  Delete "$SMPROGRAMS\$ICONS_GROUP\Website.lnk"
  Delete "$DESKTOP\易舜云手机.lnk"
  Delete "$SMPROGRAMS\$ICONS_GROUP\易舜云手机.lnk"

  RMDir "$SMPROGRAMS\$ICONS_GROUP"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd
